version: '3'
services:
  device-service:
    image: node:14-alpine
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - device-db

  device-db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
