version: "3"
services:
  device-service:
    image: node:14-alpine
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    depends_on:
      - device-db

  device-db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: device
      MYSQL_USER: root