version: "3"
services:
  frontend:
    image: nenadfilipovic/frontend:latest

  gateway:
    image: nginx:1.19.2-alpine
    ports:
      - "8080:80"
    volumes:
      - ./application/gateway/nginx.conf:/etc/nginx/nginx.conf:ro

  user-service:
    image: nenadfilipovic/user-service:latest

  device-service:
    image: nenadfilipovic/device-service:latest

  log-service:
    image: nenadfilipovic/log-service:latest

  mqtt-service:
    image: nenadfilipovic/mqtt-service:latest

  database:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./application/database:/docker-entrypoint-initdb.d

  influx-db:
    image: influxdb:1.8.2-alpine
    environment:
      INFLUXDB_DB: log
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: password

  broker:
    image: emqx/emqx
    environment:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_ACL_NOMATCH: "deny"
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http"
    volumes:
      - ./application/broker/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
      - ./application/broker/acl.conf:/opt/emqx/etc/acl.conf

  rabbitmq:
    image: rabbitmq:3.8.7-alpine
