version: "3"
services:
  client-service:
    image: nenadfilipovic/iot-dashboard/client-service

  user-service:
    image: nenadfilipovic/iot-dashboard/user-service

  device-service:
    image: nenadfilipovic/iot-dashboard/device-service

  log-service:
    image: nenadfilipovic/iot-dashboard/log-service

  receiver-service:
    image: nenadfilipovic/iot-dashboard/receiver-service

  nginx:
    image: nginx:1.19.2-alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./config/database:/docker-entrypoint-initdb.d

  influx-db:
    image: influxdb:1.8.3-alpine
    environment:
      INFLUXDB_DB: log
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: password

  emqx:
    image: emqx/emqx:4.2.1
    ports:
      - "1883:1883"
    environment:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_ACL_NOMATCH: "deny"
      EMQX_CACHE_ACL: "true"
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http"
    volumes:
      - ./config/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
      - ./config/acl.conf:/opt/emqx/etc/acl.conf

  rabbitmq:
    image: rabbitmq:3.8.9-alpine
