version: "3"
services:
  authentication-service:
    build:
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  device-service:
    build:
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  log-service:
    build:
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
