version: "3"
services:
  client:
    image: nenadfilipovic/iot-dashboard-client:latest
    depends_on:
      - nginx

  user-service:
    image: nenadfilipovic/iot-dashboard-user-service:latest
    depends_on:
      - mysql
      - rabbitmq

  device-service:
    image: nenadfilipovic/iot-dashboard-device-service:latest
    depends_on:
      - mysql
      - rabbitmq

  log-service:
    image: nenadfilipovic/iot-dashboard-log-service:latest
    depends_on:
      - influx-db
      - rabbitmq

  receiver-service:
    image: nenadfilipovic/iot-dashboard-receiver-service:latest
    depends_on:
      - emqx
      - rabbitmq

  nginx:
    image: nginx:1.19.2-alpine
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - device-service
      - log-service
      - receiver-service

  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./config/database:/docker-entrypoint-initdb.d

  influx-db:
    image: influxdb:1.8.3-alpine
    restart: on-failure
    environment:
      INFLUXDB_DB: log
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: password

  emqx:
    image: emqx/emqx:4.2.1
    restart: on-failure
    ports:
      - "1883:1883"
    environment:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_ACL_NOMATCH: "deny"
      EMQX_CACHE_ACL: "true"
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http"
    volumes:
      - ./config/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
      - ./config/acl.conf:/opt/emqx/etc/acl.conf

  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    restart: on-failure
