version: "3"
services:
    user-service:
        image: nenadfilipovic/user-service:latest
        depends_on:
            - db
    
    device-service:
        image: nenadfilipovic/device-service:latest
        depends_on:
            - db

    log-service:
        image: nenadfilipovic/log-service:latest
        depends_on:
            - db

    mqtt-service:
        image: nenadfilipovic/mqtt-service:latest
        depends_on:
            - emqx
    
    db:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./application/db:/docker-entrypoint-initdb.d

    emqx:
        image: emqx/emqx
        environment:
            EMQX_ACL_NOMATCH: 'deny'
            EMQX_ALLOW_ANONYMOUS: 'false'
            EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http"
        volumes:
            - ./application/broker/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
        depends_on:
            - user-service
            - device-service

    rabbitmq:
        image: rabbitmq:3.8.7-alpine