version: "3"
services:
  authentication-service:
    build:
      context: ./application/services/authentication
      dockerfile: Dockerfile

  device-service:
    build:
      context: ./application/services/device
      dockerfile: Dockerfile

  log-service:
    build:
      context: ./application/services/log
      dockerfile: Dockerfile
