#-------------------------------------------------------------------------------------------------------------
# Configuration file for Dockerfile used for development container.
# Dockerfile
#-------------------------------------------------------------------------------------------------------------

# Select base image.
FROM node:14-alpine

# ** [Optional] Uncomment this section to install additional packages. **
#
# RUN apt-get update \
#     && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>